name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
      name: "Meu Primeiro Job"
      runs-on: ubuntu-latest
      steps:
        - name: "Minha primeira acao"
          run: echo "Hello World !!!"
        - name: "Segunda acao"
          run: |  
            echo "Voce criou o seu primeiro workflow !!!"
            echo "Parabens"
        - name: "Script python"
          run: |
              variavel = "Pythonzeira !!!"
              print(variavel)
          shell: python
  segundo-job:
    name: "Instalacao do Ambiente NodeJS"
    runs-on: ubuntu-latest
    steps: 
        - name: "Verificacao da versao do NodeJS atual"
          run: node --version
        - name: "Definicao da versao 20 e pouco do NodeJS"
          uses: actions/setup-node@v4
          with:
            node-version: '20.13.1'
        - name: "Verificacao da versao do NodeJS depois de utilizar a action de atualizacao"
          run: node --version


      

        




